import os
import re
import html
import datetime
import urllib.parse
import urllib.request

from core import config

UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}


def _get(url, timeout=10):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=timeout) as r:
        charset = r.headers.get_content_charset() or "utf-8"
        return r.read().decode(charset, "ignore")


def search(query, limit=5):
    q = urllib.parse.quote(query)
    url = f"https://html.duckduckgo.com/html/?q={q}"
    try:
        page = _get(url)
    except Exception:
        return []
    results = []
    for m in re.finditer(r'<a[^>]+class="result__a"[^>]+href="([^"]+)"[^>]*>(.*?)</a>', page, re.S):
        href, title = m.group(1), _strip(m.group(2))
        real = _unwrap(href)
        if real and title:
            results.append({"title": title, "url": real})
        if len(results) >= limit:
            break
    return results


def _unwrap(href):
    if "uddg=" in href:
        m = re.search(r"uddg=([^&]+)", href)
        if m:
            return urllib.parse.unquote(m.group(1))
    if href.startswith("http"):
        return href
    return None


def _strip(s):
    s = re.sub(r"<[^>]+>", "", s)
    return html.unescape(s).strip()


def extract_text(url, max_chars=2500):
    try:
        page = _get(url)
    except Exception:
        return ""
    page = re.sub(r"<(script|style|nav|footer|header)[^>]*>.*?</\1>", " ", page, flags=re.S | re.I)
    paras = re.findall(r"<p[^>]*>(.*?)</p>", page, re.S | re.I)
    text = " ".join(_strip(p) for p in paras)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:max_chars]


def summarize(text, max_sentences=3):
    sentences = re.split(r"(?<=[.!?])\s+", text)
    sentences = [s for s in sentences if len(s) > 40]
    return " ".join(sentences[:max_sentences])


def build_report(query, progress=None):
    def report(msg):
        if progress:
            progress(msg)

    report(f"Searching for “{query}”…")
    hits = search(query, limit=5)
    if not hits:
        return None, "No results found."

    sources = []
    for i, hit in enumerate(hits, 1):
        report(f"Reading source {i} of {len(hits)}…")
        body = extract_text(hit["url"])
        if body:
            hit["summary"] = summarize(body)
            sources.append(hit)

    if not sources:
        return None, "Couldn't read any sources."

    report("Writing report…")
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# Research Report: {query}",
        f"\n*Generated by Beaver · {now}*\n",
        f"## Overview\n",
        f"Compared {len(sources)} sources on “{query}”. Key findings from each below.\n",
        "## Sources\n",
    ]
    for i, s in enumerate(sources, 1):
        lines.append(f"### {i}. {s['title']}")
        lines.append(f"<{s['url']}>\n")
        lines.append(f"{s['summary'] or '(no extractable summary)'}\n")

    lines.append("## Comparison\n")
    lines.append(_compare(sources))

    md = "\n".join(lines)

    os.makedirs(config.REPORTS_DIR, exist_ok=True)
    safe = re.sub(r"[^a-z0-9]+", "_", query.lower()).strip("_")[:40]
    path = os.path.join(config.REPORTS_DIR, f"report_{safe}.md")
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(md)
    except Exception:
        path = None

    return {"markdown": md, "path": path, "sources": sources}, None


def _compare(sources):
    titles = [s["title"] for s in sources]
    text_all = " ".join(s.get("summary", "") for s in sources).lower()
    words = re.findall(r"\b[a-z]{5,}\b", text_all)
    stop = {"about", "there", "their", "these", "those", "which", "where",
            "would", "could", "should", "other", "between", "because"}
    freq = {}
    for w in words:
        if w not in stop:
            freq[w] = freq.get(w, 0) + 1
    common = sorted(freq, key=freq.get, reverse=True)[:8]
    out = f"All {len(sources)} sources were reviewed. "
    if common:
        out += "Recurring themes across them include: " + ", ".join(common) + ". "
    out += "See each source above for its specific take."
    return out
